// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/atomic-redesign/AuroraGlass.tsx": () => import("../components/mockups/atomic-redesign/AuroraGlass.tsx"),
  "./components/mockups/atomic-redesign/NeonixCyberpunk.tsx": () => import("../components/mockups/atomic-redesign/NeonixCyberpunk.tsx"),
  "./components/mockups/atomic-redesign/ZenMinimal.tsx": () => import("../components/mockups/atomic-redesign/ZenMinimal.tsx")
};
